/* Cardápios levantados em 23/09/2026. Preços podem ter mudado — cada um traz a fonte e a data. */
const CARDAPIOS = {
  crescente: {
    fonte: "Site oficial (crescentegastronomia.com.br/cardapio)",
    fonteUrl: "https://crescentegastronomia.com.br/cardapio/",
    atualizado: "set/2026",
    secoes: [
      { titulo: "Entradas", itens: [
        ["Personal", "Salada de folhas orgânicas e molho de aipo", 68],
        ["Suppli de queijo colonial", "Cabra e pesto de beterraba", 73],
        ["Brie em fina massa", "Pera e calda ao cardamomo", 87],
        ["Para divertir a boca", "Patês e outras delícias com pães e biscoitos salgados da casa", 84],
        ["Portobello e shiitake", "Em crumble de parmesão", 92],
      ]},
      { titulo: "Sopas", itens: [
        ["Ervilha e hortelã frescas", "Com crocante e azeite de sementes", 77],
        ["Toque thai de camarão", "Pimenta, cogumelo, gengibre e capim-limão", 96],
      ]},
      { titulo: "Saladas", itens: [
        ["Terrine de coelho", "Ao vinho branco e pera grelhada", 96],
        ["Tortinha de cogumelo", "Alface orgânica e pato defumado", 98],
        ["Queijo de cabra morno", "Figos, mostarda Dijon e bacon", 98],
      ]},
      { titulo: "Peixes e frutos do mar", itens: [
        ["Truta à baronesa", "Crosta de amêndoas, banana, creme de baroa com toque de gorgonzola", 128],
        ["Salmão mediterrâneo", "Grelhado no azeite, tomate ao creme e legumes", 132],
        ["Pescado do dia em crosta de coco", "Com \"nhoque\" grelhado de banana-da-terra", 136],
        ["Camarão thai", "Ao curry, com arroz e coco", 138],
        ["Vulcão submarino", "Pescado, camarão, vieira, alho-poró e champignon", 143],
        ["Tentáculo de polvo grelhado", "Nhoque de batata, salmão e espinafre", 158],
        ["Ravioli de camarão ao tucupi", "Pasta fresca", 133],
      ]},
      { titulo: "Carnes e aves", itens: [
        ["Filé com crocante de bacon", "Batata laminada e palmito local in natura", 137],
        ["Entrecôte ao caramelo balsâmico", "Queijo de cabra crocante, figo grelhado e parma", 128],
        ["Coelho ao alecrim", "Cogumelos e guioza de vegetais", 129],
        ["Picanha de cordeiro ao tamarindo", "Cuscuz com pistache e especiarias (leve picância)", 158],
        ["Galinha-d'angola", "Peito grelhado com tomilho e coxa confitada, dumpling de ricota com maçã verde", 131],
        ["Magret de canard aux pistaches", "Pato com batata laminada e tempurá de vagem", 139],
        ["Canard em três texturas", "Harumaki, magret, confit e gohan levemente tostado", 139],
      ]},
      { titulo: "Equilíbrio (sem carne)", itens: [
        ["Shiitake salteado", "Vegetais grelhados e arroz 7 grãos com nozes", 118],
        ["Dahl de lentilha", "Salmão, gengibre, cogumelo e arroz basmati", 127],
      ]},
      { titulo: "Sobremesas", itens: [
        ["Trilogia de sorvetes da casa", "Consulte os sabores", 36],
        ["Fondant au chocolat", "Sobre creme inglês", 36],
        ["Profiteroles", "Carolinas crocantes (15 min de preparo)", 44],
        ["Crumble de frutas vermelhas", "Blueberry, framboesa, morango e amora (15 min)", 46],
        ["Clafoutis de maçã ao damasco", "", 46],
        ["Crepe de massa de chocolate", "Recheado de sorvete (15 min)", 62],
      ]},
    ],
    nota: "Menu executivo (entrada + prato + sobremesa, R$ 128) só em almoço de segunda, quinta e sexta, exceto feriados.",
  },

  astral: {
    fonte: "Cardápio em PDF do site oficial (astralgastronomia.com.br)",
    fonteUrl: "https://astralgastronomia.com.br/wp-content/uploads/2024/02/Cardapio-Astral-2024.pdf",
    atualizado: "2024 — preços podem ter subido",
    secoes: [
      { titulo: "Entradas", itens: [
        ["Trio de camarões Astral", "3 camarões graúdos recheados com cream cheese, empanados no panko e coco, salada crocante e chutney de manga", 59],
        ["Lula à dorê", "Lula crocante no panko com aioli de wasabi", 45],
        ["Dadinhos de tapioca", "Com queijo coalho e geleia de pimenta", 35],
        ["Croquete estilo alemão", "5 croquetes de carne com mostarda escura", 35],
        ["Couvert Astral", "Geleia, patê e conserva da casa com torradas", 35],
        ["Patê de truta", "Com cesto de torradas", 29],
        ["Patê de fígado", "Fígado de galinha com cesto de torradas", 29],
      ]},
      { titulo: "Especiais da estação", itens: [
        ["Pato confit", "Molho de tamarindo e mel, risoto de gorgonzola com nozes, damasco e maçã", 129],
        ["Polvo", "Cozido lentamente, batatas ao murro, purê de abóbora cabotiá e sementes crocantes", 135],
        ["Lombo de bacalhau", "Confitado no azeite, batatas ao murro, tapenade, creme de alho, pimentões e cebolas confitadas", 139],
      ]},
      { titulo: "Carnes e peixes", itens: [
        ["Truta com espuma de baroa", "Molho de amêndoas e manteiga noisette, salada de quinoa", 79],
        ["Salmão com risoto de grana", "Salmão grelhado e risoto cítrico de grana padano", 95],
        ["Kafta de cordeiro", "Salada mediterrânea, homus e chips de tortilha", 79],
        ["Cordeiro Astral", "Marinado 48h, cozido 72h, purê de ervilha com hortelã e batatas ao murro", 95],
        ["Medalhão com piamontese", "Filé mignon ao molho madeira, arroz piamontese com cogumelos e fritas", 79],
        ["Denver com fettuccine", "Corte marmorizado com fettuccine na fonduta de grana", 129],
        ["Denver com aligot", "Demi-glace de vinho do Porto e aligot de gruyère", 115],
        ["Costela com aligot", "Black Angus assada por 12h, demi-glace de Porto e aligot", 109],
        ["Filé com aligot", "Filé mignon, demi-glace de Porto e aligot de gruyère", 89],
        ["Boeuf bourguignon", "Carne braseada no vinho com cogumelos e cebola glaceada, arroz ou fettuccine", 79],
      ]},
      { titulo: "Massas da casa", itens: [
        ["Nhoque de aipim", "Pomodoro e manjericão, com grana ralado", 65],
        ["Spaghetti com shiitake", "Manteiga, alho dourado, salsinha e azeite trufado", 65],
        ["Fettuccine ao pomodoro", "Molho de tomate artesanal e manjericão", 65],
        ["Fettuccine com fonduta de grana", "Molho cremoso de grana padano", 75],
        ["Fettuccine del mar", "Nero di seppia com camarões e salmão na manteiga de sálvia e limão-siciliano", 109],
        ["Fettuccine nero com bisque", "Camarões, anéis de lula e bisque", 109],
        ["Fettuccine com camarões ao pomodoro", "Camarões argentinos e manjericão", 109],
        ["Nhoque de aipim com camarões", "Pomodoro e philadelphia", 119],
        ["Camarões da Norma", "Com pomodoro e philadelphia, arroz e batatas fritas", 119],
      ]},
      { titulo: "Sobremesas", itens: [
        ["Torta alemã", "Biscoito maisena e ganache de chocolate", 20],
        ["Mil-folhas", "Massa folhada da casa com creme de confeiteiro", 20],
        ["Tartelete de banoffee", "Sablée de amêndoas, doce de leite da casa, banana e chantilly", 25],
        ["Mousse de chocolate com avelãs", "Meio amargo com caramelo salgado", 29],
        ["Pecan pie", "Sablée de amêndoas com noz-pecã e toque de bourbon", 29],
        ["Pecan pie com sorvete", "Com sorvete de baunilha artesanal", 39],
      ]},
    ],
    nota: "Camarões argentinos podem virar 200 g de camarão VG (+R$ 80).",
  },

  anexo: {
    fonte: "Destaques do Instagram @anexo.gastro",
    fonteUrl: "https://www.instagram.com/anexo.gastro/",
    atualizado: "ago/2026 — o Instagram não mostra preços",
    secoes: [
      { titulo: "Entradas", itens: [
        ["Truffle Fries Specialle", "Fritas da casa com espuma aerada de parmesão, azeite trufado e sal de alecrim", null],
        ["Burrata", "Banhada em pomodoro com tomates confit, pesto fresco e redução de balsâmico", null],
        ["Ceviche de polvo", "Marinado em leite de tigre com manga e dedo-de-moça, chips de banana-da-terra", null],
        ["Gambas pil pil", "Camarões salteados no alho dourado e páprica defumada, com pão de fermentação natural", null],
        ["Trio Burguer Anexo", "3 mini hambúrgueres no brioche com bacon crocante, brie e geleia de pimenta", null],
      ]},
      { titulo: "Principais", itens: [
        ["Beef Wellington", "Filé envolto em massa folhada", null],
        ["Fraldinha Red & Gnocchi", "Nhoque de batata, espuma de queijos e nozes caramelizadas", null],
        ["Pappardelle da casa", "Massa fresca com ragu de short rib (prato da semana)", null],
        ["Salmão", "Purê de banana-da-terra, crispy de cebola e pesto", null],
      ]},
      { titulo: "Pizzas", itens: [
        ["Speciale Parma", "Parma, pesto, nozes caramelizadas, mel defumado, pomodoro e mozzarella", null],
        ["Al mare", "Bisque de frutos do mar, mozzarella e camarão", null],
      ]},
    ],
    nota: "A casa agora se chama Anexo Gastrô, com cozinha de toque italiano e bar de drinks autorais. Também tem saladas, risotos, sobremesas e carta de vinhos. O cardápio completo com preços é na mesa ou pelo WhatsApp (22) 99747-2499.",
  },

  gigi: {
    fonte: "Foto do cardápio enviada no Restaurant Guru",
    fonteUrl: "https://restaurantguru.com.br/Emporio-do-Amor-Nova-Friburgo/menu",
    atualizado: "cerca de 1 ano atrás",
    secoes: [
      { titulo: "Entradas", itens: [
        ["Entradinha da casa", "Pães, manteiga, geleia especial, pastas, patês e vinagretes (opções do dia)", 32],
        ["Bolinho de bacalhau", "Porção com 5 unidades", 33],
        ["Mini linguiças", "Com mostardas e pães", 33],
        ["Harumaki", "Camarão ou legumes", 33],
        ["Sopa do dia", "Consulte as opções", 27],
        ["Mini salada", "", 20],
      ]},
      { titulo: "Pratos individuais", itens: [
        ["Peixe grelhado", "No azeite com especiarias e legumes assados", 77],
        ["Truta grelhada", "Com amêndoas e batatas gratinadas com queijo", 80],
        ["Mignon grelhado", "Molho francês e batatas arrepiadas", 86],
        ["Estrogonofe de mignon", "", 70],
        ["Rosti de camarão", "", 70],
        ["Rosti de cogumelos", "", 68],
        ["Prato da horta", "Legumes orgânicos, azeite e ervas", 60],
        ["Estrogonofe de cogumelos", "", 66],
        ["Massa especial", "Camarão ou cogumelos", 39],
      ]},
      { titulo: "Sobremesas", itens: [
        ["Pudim", "", 12],
        ["Torta de maçã", "Maçãs, damascos e lascas de amêndoas", 23],
        ["Rabanada da casa", "", 28],
        ["Mousse três chocolates", "", 28],
        ["Profiteroles", "Com sorvete e calda quente de chocolate", 30],
        ["Morango Empório", "Massa choux, morangos, creme especial e calda de morangos frescos", 35],
      ]},
      { titulo: "Bebidas", itens: [
        ["Sucos especiais", "Limonada das Neves, Limonada dos Sonhos, Drink Empório", 19],
        ["Sucos", "Laranja, abacaxi, limonada suíça, morango", 15],
        ["Cerveja long neck", "330 ml", 13],
        ["Expresso", "Pequeno R$ 8,50 · duplo R$ 15", 8.5],
        ["Caipirinha, vinhos e cerveja artesanal", "Consulte", null],
      ]},
    ],
    nota: "Sexta e sábado também tem jantar das 19h às 21h, só com reserva antecipada.",
  },

  mariquinha: {
    fonte: "Instagram @restaurantedonamariquinha e avaliações do TripAdvisor",
    fonteUrl: "https://www.instagram.com/restaurantedonamariquinha/",
    atualizado: "set/2026",
    secoes: [
      { titulo: "Rodízio de comida caseira (desde 1952)", itens: [
        ["Entradas na mesa", "Saladas e torresmo", null],
        ["Salgadinhos da casa", "Pastelzinho de carne, bolinho de batata-baroa e bolinho de vagem", null],
        ["Carnes", "Bife, bife à milanesa e bife à parmegiana", null],
        ["Acompanhamentos", "Arroz, feijão, batata frita e o que mais sair da cozinha no dia", null],
      ]},
    ],
    nota: "É um rodízio, então vai chegando de tudo à mesa. Almoço de terça a domingo, das 11h45 às 15h. O preço por pessoa é confirmado por telefone: (22) 2522-2309.",
  },

  spaghetti: {
    fonte: "Foto do cardápio enviada no Restaurant Guru",
    fonteUrl: "https://restaurantguru.com.br/Spaghetti-Cozinha-Italiana-Brazil/menu",
    atualizado: "cerca de 8 meses atrás",
    secoes: [
      { titulo: "Entradas", itens: [
        ["Bruschetta clássica", "4 unidades com pomodoro e parmesão", 40.9],
        ["Bruschetta especial", "4 unidades", 54.9],
        ["Confit de melanzana", "Berinjela confitada com parmesão e torradas", 48.9],
        ["Delizia bianca", "Pizza branca com provolone e alecrim, pesto de manjericão, sardela e stracciatella", 68.9],
        ["Fresca di Puglia", "Pizza branca com provolone e alecrim, burrata, pesto, parma e mel", 87.9],
      ]},
      { titulo: "Massas (spaghetti, fettuccine, pappardelle ou nhoque gratinado)", itens: [
        ["Aglio, olio e peperoncino", "", null],
        ["Pomodoro", "Molho de tomate e manjericão", null],
        ["Salsa bianca", "Molho branco de manteiga, leite e especiarias", null],
        ["Amatriciana", "Pomodoro, bacon, azeitonas, tomate-cereja, manjericão e pimenta-biquinho", 74.9],
        ["Bolognesa", "Pomodoro, carne moída, azeitona preta e ervas frescas", 76.9],
        ["Gricia", "Molho branco com bacon, parmesão e pimenta-do-reino", 81.9],
        ["Cacio e pepe", "Molho branco, gouda, parmesão e pimenta calabresa", 78.9],
        ["Cacio", "Molho branco, queijo gouda e parmesão", 78.9],
        ["Salsa di quattro formaggi", "Mussarela, parmesão, gorgonzola e gouda", 84.9],
        ["Pollo", "Molho branco com frango desfiado, alho e ervas", 74.9],
        ["Calábria", "Pomodoro, pepperoni, azeitonas, pimenta-biquinho e ervas", 78.9],
      ]},
      { titulo: "Especiais da serra", itens: [
        ["Spaghetti al limone", "Creme ao limone, raspas de limão e truta na manteiga com alcaparras", 96.9],
        ["Fettuccine ao pesto", "Pesto de manjericão, truta na manteiga com shiitake e parmesão maçaricado", 104.9],
      ]},
      { titulo: "Adicionais", itens: [
        ["Cesta de pão", "", 7.9],
        ["Extra de parmesão", "", 13.9],
        ["Isca ou medalhão de mignon", "150 g", 28.9],
        ["Camarão", "150 g", 28.9],
        ["Chorizo", "", 28.9],
        ["Bacon ou molho pomodoro", "", 12.9],
      ]},
    ],
    nota: "Também servem pizzas. Os preços das três primeiras massas não ficaram legíveis na foto.",
  },

  segredo: {
    fonte: "Instagram @segredocozinhaintimista e guia da Pousada Canteiros",
    fonteUrl: "https://www.instagram.com/segredocozinhaintimista/",
    atualizado: "2026 — sem preços publicados",
    secoes: [
      { titulo: "Pratos da casa", itens: [
        ["T-bone", "Com batatas assadas e salada Segredo", null],
        ["Lombo de bacalhau", "Com batatas ao murro e brócolis salteados", null],
        ["Filé à parmegiana", "Receita tradicional da Dona Lourdes", null],
        ["Feijoada nobre", "", null],
        ["Nhoque de aipim", "", null],
        ["Tapas da Catalunha", "", null],
        ["Salada Segredo", "Mini alfaces orgânicas, picles de rabanete, pimentões assados e picles de beterraba", null],
      ]},
    ],
    nota: "São poucas mesas e o cardápio muda. Eles adaptam os pratos a restrições se você avisar na reserva: (22) 99748-7377.",
  },

  parvati: {
    fonte: "Foto do cardápio enviada no Restaurant Guru",
    fonteUrl: "https://restaurantguru.com.br/Parvati-de-Lumiar-Lumiar/menu",
    atualizado: "cerca de 8 meses atrás",
    secoes: [
      { titulo: "Na brasa (preço para 1 / 2 / 3 / 4 pessoas)", itens: [
        ["Picanha na brasa", "Arroz, feijão, farofa, vinagrete, linguiça e fritas, rústica ou aipim · 1p R$ 99 · 2p R$ 149 · 3p R$ 189 · 4p R$ 229", 149],
        ["Churrasco misto completo", "Contrafilé, frango, suíno e linguiça com os mesmos acompanhamentos · 2p R$ 149 · 3p R$ 189 · 4p R$ 229", 149],
        ["Salmão na brasa", "Arroz com brócolis, salada e fritas · molho de alcaparras, laranja, mostarda e mel ou amêndoas · 1p R$ 99 · 2p R$ 149", 149],
        ["Truta na brasa", "Arroz, feijão, purê de banana-da-terra, salada e fritas · 1p R$ 79 · 2p R$ 140", 140],
        ["Filé de linguado grelhado", "Arroz com brócolis, feijão, salada e fritas · 1p R$ 74 · 2p R$ 114", 114],
        ["Filé de linguado com camarão", "1p R$ 89 · 2p R$ 139", 139],
        ["Truta simples", "Filé de truta com molho à escolha (individual)", 49],
      ]},
      { titulo: "Massas (monte seu prato)", itens: [
        ["Fettuccine, nhoque ou espaguete", "Ao sugo, gorgonzola ou branco, com frango, shiitake ou bolonhesa", 59],
        ["Com camarão ou filé mignon", "", 74],
      ]},
      { titulo: "Aperitivos e porções", itens: [
        ["Camarão alho e óleo", "", 75],
        ["Carne de sol com aipim", "", 79],
        ["Costela BBQ", "Com fritas, rústica ou aipim", 95],
        ["Isca de mignon", "Molho gorgonzola, farofa e fritas", 115],
        ["Isca de linguado", "Molho rosé ou barbecue", 89],
        ["Picanha aperitivo", "Farofa, vinagrete e fritas", 110],
        ["Linguiça artesanal", "400 g de linguiça frita", 54],
        ["Bolinhos de bacalhau ou truta", "", 45],
        ["Bolinho de carne-seca com gorgonzola", "", 49],
        ["Pastéis (4 un.)", "Carne, queijo ou frango com catupiry R$ 22 · camarão R$ 26", 22],
        ["Batata frita", "Simples R$ 30 · com bacon e cheddar R$ 40 · rústica R$ 39", 30],
        ["Aipim", "Simples R$ 30 · com parmesão R$ 40", 30],
        ["Salada do chef", "Mix de folhas e vegetais da estação", 29],
      ]},
    ],
    nota: "Onde tem mais de um preço, o valor em destaque é para 2 pessoas. O executivo (R$ 30–39) é só de segunda a sexta, exceto feriados.",
  },
};
